openapi: 3.0.1
info:
  title: Analyst Insights API
  version: '1.0'
servers:
  - url: https://api.benzinga.com/api/v1
paths:
  /analysts/insights:
    get:
      summary: Get analyst insights
      operationId: getAnalystInsights
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: Authentication token required to access the API.
        - name: ticker
          in: query
          required: true
          schema:
            type: string
          description: The ticker symbol of the security to get insights for.
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page number of the insights pagination.
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Number of insights per page.
      responses:
        '200':
          description: A list of analyst insights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystInsightsResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
components:
  schemas:
    AnalystInsightsResponse:
      type: object
      properties:
        analyst-insights:
          type: array
          items:
            $ref: '#/components/schemas/AnalystInsight'
    AnalystInsight:
      type: object
      properties:
        action:
          type: string
        analyst_insights:
          type: string
        date:
          type: string
          format: date
        firm:
          type: string
        firm_id:
          type: string
        id:
          type: string
        pt:
          type: string
        rating:
          type: string
        rating_id:
          type: string
        security:
          $ref: '#/components/schemas/Security'
        updated:
          type: integer
    Security:
      type: object
      properties:
        cik:
          type: string
        exchange:
          type: string
        isin:
          type: string
        name:
          type: string
        symbol:
          type: string
