openapi: 3.1.0
info:
  title: Bull/Bear API
  description: >
    An API that provides Bullish and Bearish synopses based on a compilation of analyst research reports.
  version: 1.0.0
servers:
- url: https://api.benzinga.com/api/v1
paths:
  "/bull-bear":
    get:
      summary: Retrieve a Bull/Bear synopsis
      tags:
        - bull_bear
      parameters:
        - name: bull_bear
          in: path
          description: The unique identifier for the Bull/Bear object.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BullBear"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type.
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem.
      required:
        - type
        - status
      additionalProperties: false
    BullBear:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the Bull/Bear object.
        created_at:
          type: string
          format: date-time
          description: Time at which the Bull/Bear object was created.
        updated_at:
          type: string
          format: date-time
          description: Time at which the Bull/Bear object was last updated.
        ticker:
          type: string
          description: The security for which the Bull/Bear statements are provided.
        bull_case:
          type: string
          description: Bullish synopsis of analyst reports. Investors can read and decide which statement they associate with.
        bear_case:
          type: string
          description: Bearish synopsis of analyst reports.
        analyst_firms_referenced:
          type: integer
          description: The count of analyst research reports that were referenced to compile the statements.
      required:
        - id
        - created_at
        - updated_at
        - ticker
        - bull_case
        - bear_case
        - analyst_firms_referenced
      additionalProperties: false
  securitySchemes:
    apiKey:
      type: apiKey
      description: API Keys in the query parameters are used to authenticate this endpoint.
      name: apiKey
      in: query
security:
  - apiKey: []

tags:
  - name: bull_bear
    description: >
      This endpoint returns bullish and bearish synopses based on a collection of analyst research reports.
    externalDocs:
      url: https://datatracker.ietf.org/doc/html/rfc7807
