openapi: 3.0.1
info:
  title: Bulls Say / Bears Say
  description: Get the bullish and bearish statements
  version: "1.0"
servers:
- url: https://api.benzinga.com/api/v1
security:
- token: []
paths:
  /bulls_bears_say:
    get:
      summary: Get the bullish and bearish cases of a particular security based on analysis of sell side analyst research reports.
      parameters:
      - name: accept
        in: header
        description: Specify return format.
        schema:
          type: string
          default: application/json
          enum:
          - application/json
      - name: symbols
        in: query
        description: One or more comma separated symbols to specify companies to get
          data for.
        schema:
          type: string
          format: csv
      - name: from
        in: query
        description: 'Date to query from point in time. Sorted by published date.
          If "YTD" Sets from to the first trading day of the current year.  Some other
          valid values: "1MONTH", "1m", "1M" (all meaning "1 month  from today"),
          "1d", "1D" (both meaning "1 day from today").'
        schema:
          type: string
          format: YYYY-MM-DD, or any of YTD, iMONTH, iM, iD
      - name: to
        in: query
        description: Date to query to point in time. Sorted by published date.
        schema:
          type: string
          format: YYYY-MM-DD, or any of iMONTH, iW, iD, iH, iM
      - name: interval
        in: query
        description: 'The candle intervals to use, i.e., 5 minute bars, daily bars,
          etc. Some valid values: 1MONTH, 1W, 1D, 1H (1 hour), 2H, 3H, 4H, 5M (5 minutes),
          10M, 15M, 30M. Defaults to an appropriate value based on the period of data
          requested: i.e., 5 minutes bars if less than 5 days, daily bars if greater.'
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BullBear'
components:
  schemas:
    BullBear:
      type: object
        bulls_say_bears_say:
          type: array
          description: An array of bullish and bearish cases.
          items:
            type: object
            properties:
              bear_case:
                type: string
                description: The bearish case for a particular security. 
                format: float
              bull_case:
                type: number
                description: The bullish case for a particular security. 
                format: float
              id:
                type: number
                description: The unique identifier for the object 
                format: float
              ticker:
                type: number
                description: The security being mentioned. 
                format: float
              updated:
                type: timestamp
                description: The unix timestamp of the last update to the record. 
                format: float    
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: query
