---
openapi: 3.0.1
info:
  title: Newsfeed (Streaming) v1
  description: >-
    This Websocket API streams Benzinga Newsfeed Content realtime.

    An always-on connection delivers news the instant it becomes available.

    Example client implementation available at
    https://github.com/Benzinga/websocket-feed-examples.

    You may find tools like https://websocketking.com helpful for testing.
  version: 1.0.0
servers:
  - url: wss://api.benzinga.com/api/v1/news
security:
  - token: []
paths:
  /stream:
    get:
      summary: Stream Newsfeed
      description: >-
        Server will automatically send PING control frames to connected clients,
        but does not require response. Many client libraries will automatically
        respond with PONG control frames; this is desirable, but not required.
        Sending any message over websocket  to the server other than PING/PONG
        control frames will result in immediate disconnection.
      responses:
        '101':
          description: >-
            ok, websocket connection established and ready. *Note messages are
            sent as single messages, not an array,  but documentation spec does
            not have support for Websocket message type.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StreamMessage'
            application/json:
              example:
                api_version: websocket/v1
                kind: News/v1
                data:
                  action: Created
                  id: 1234567890
                  content:
                    id: 2353787
                    revision_id: 6421725
                    type: story
                    created_at: 2012-02-17T21:01:39.000Z
                    updated_at: 2020-02-05T11:31:08.000Z
                    title: Company A reports record earnings in Q1
                    body: >-
                      During a Pre-Market earnings annoucement Company A
                      reported ...
                    authors:
                      - Scott Rubin
                    teaser: During a Pre-Market earnings annoucement ...
                    url: >-
                      https://www.benzinga.com/news/21/05/2353787/company-a-makes-big-moves
                    tags:
                      - Earnings
                    securities:
                      - symbol: GOOG
                        exchange: NASDAQ
                        primary: false
                    channels:
                      - News
                      - Movers & Shakers
                  timestamp: 2012-02-17T21:01:39.000Z
        '401':
          description: Unauthorized. Missing or Invalid key.
          content: {}
        '429':
          description: >-
            Too Many Connections. A single API key can only have one
            simultaneous connection. You may need to backoff and try again if
            you had a recent disconnection.
          content: {}
components:
  schemas:
    StreamMessage:
      required:
        - api_version
        - data
        - kind
      type: object
      properties:
        api_version:
          type: string
          description: Indicates the message API version. Currently `websocket/v1`.
        kind:
          type: string
          description: Indicates the message data Kind. Currently `News/v1`.
        data:
          $ref: '#/components/schemas/StreamMessageData'
    StreamMessageData:
      required:
        - action
        - id
        - timestamp
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the event that triggered the action.
        action:
          type: string
          description: Indicates what type of status change is occured for this news item.
          enum:
            - Created
            - Updated
            - Removed
        timestamp:
          type: string
          description: Indicates event time. (string:RFC3339Milli)
        content:
          $ref: '#/components/schemas/NewsContent'
      description: Message payload
    NewsContent:
      type: object
      properties:
        id:
          type: integer
          description: >-
            The unique identifier of the article. This identifier is also found
            in the path of url on benzinga.com. Does not change when story is
            updated.
        revision_id:
          type: integer
          description: >-
            The unique identifier of the article revision. Changes when story is
            updated.
        type:
          type: string
          description: Article type/source. ex. 'story'.
        created_at:
          type: string
          description: >-
            The moment the article is first published. This timestamp will not
            change on revisions. (RFC3339Milli)
          format: 2012-02-17T21:01:39.000Z
        updated_at:
          type: string
          description: >-
            The timestamp of the last update to the article. This timestamp is
            updated for each revision. (RFC3339Milli)
          format: 2012-02-17T21:01:39.000Z
        title:
          type: string
          description: >-
            The headline of the article. This will only be plain text. May be
            updated with revisions.
        body:
          type: string
          description: >-
            The article content. This field can contain html and html encoded
            characters such as `&amp` or `&#46` etc. You may request plaintext
            only with HTML removed, but this may impact formatting/style and
            produce results different from what the source intended.
        authors:
          type: object
          properties: {}
          description: >-
            The authors of the article. This could be a Benzinga journalist,
            news desk analyst or contributor on benzinga.com.
        teaser:
          type: string
          description: >-
            Depending on where the content is originated from (Benzinga.com or
            Benzinga Pro terminal) the teaser functions in different ways. If
            the article is a full length article from Benzinga.com, where the
            body field is filled out, this will be the first sentence of the
            article up to 256 characters. If this is a Benzinga Pro headline,
            this will function like the body of an article and provide
            additional context to the headline, usually no more than a few
            paragraphs.
        url:
          type: string
          description: >-
            The url where the article lives on Benzinga.com. If this is a pro
            headline, it will take the user to a shortened headline with a
            paywall to purchase the Benzinga Pro terminal, so use with caution.
        channels:
          type: array
          description: >-
            The topic(s) or categories that relate to the article. Channels can
            have sub-channels, but they will all be listed as their own item and
            not as a sub-level of the array. Why Is It Moving (WIIM) data will
            be labeled with the `WIIM` channel.
          items:
            type: string
        securities:
          type: array
          description: >-
            The securities that are listed within the article body. This will
            not display competitor symbols unless they are specifically
            referenced in the article. Additional fields beyond name are not
            enabled by default and must be enabled by Benzinga staff.
          items:
            required:
              - symbol
            type: object
            properties:
              symbol:
                type: string
              primary:
                type: boolean
              exchange:
                type: string
        tags:
          type: array
          description: >-
            Additional tags that are not channels or categories, but are
            reoccuring themes including, but not limited to; analyst names,
            bills being talked about in Congress (Dodd-Frank), specific products
            (iPhone), politicians, celebrities, stock movements (i.e. 'Mid-day
            Losers' & 'Mid-day Gainers').
          items:
            type: string
      description: News object data
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: query
